import Head from "next/head";
import styles from "../styles/Home.module.css";
import Homeo from "./components/Home";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />

      </Head>
<Homeo />
      </div>
  );
}
