import React from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import { useRouter } from 'next/router'
import {useState} from 'react'
import axios from 'axios';
import Nav from './Nav';
import Leftsidebar from './LeftSidebar';

const preventDefault = f => e => {
  e.preventDefault()
  f(e)
}
export default function AddWorker({href}) {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [name, setName] = useState('')
  const [phone, setPhone] = useState(0)
  const [loc, setLoc] = useState('')


    
    function handleParamemail  (e) {
      setEmail(e.target.value)

    


  }
  function handleParamusername  (e) {
    
    setName(e.target.value)
    
 console.log(name);
 

}
 function handleParamPhone (e) {
    
    setPhone(e.target.value)
    
 
 

}
function handleParamLoc (e) {
    
  setLoc(e.target.value)
  



}
    function handleSubmit ()  {
  
     axios.post('http://localhost:3000/api/Workers/createWorkers',
     {
         name: name,
         email:email,
         phone:Number(phone),
         localisation:loc
       }
      ).then((res)=> 
       console.log(res.data))
       .catch((err)=>console.log(err))
    }
    return (
        <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />
 <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"></script>
      </Head>    
      
    <div id="main-wrapper">
    
    <Nav />
    <Leftsidebar />
    <div className="page-wrapper">
    
      <div className="container-fluid">
       
      <div className="flex flex-row" >
          <div className="w-4/12"></div>
          <div className="w-3/12 flex-col min-h-screen">
              <div  className="h-1/6">
              </div>
              <div  className="h-3/6">

                
                  <div
                    className="
                      d-flex
                      no-block
                      align-items-center
                      p-3
                      bg-primary
                      text-white
                      mb-2
                    "
                  >
                    <div className="">
                      <img
                        src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                        alt="user"
                        className="rounded-circle"
                        width="60"
                      />
                    </div>
                    <div className="ms-2">
                      <h4 className="mb-0 text-white">Add</h4>
                      <p className="mb-0">new worker</p>
                    </div>
                  </div>
                  <div
                  className="form-horizontal mt-3 form-material"
                  id="loginform"
                  
                >
                     <div className="form-group mb-3">
                    <div className=" ">
                      <input
                        className="form-control text-center"
                        type="email"
                        required=""
                        value={email}
                        onChange={handleParamemail}

                        placeholder="Email"
                      />
                    </div>
                  </div>
                  <div className="form-group mb-3">
                    <div className=" ">
                      <input
                        className="form-control text-center"
                        type="text"
                        required=""
                        value={name}
                       onChange={handleParamusername}
                        placeholder="Username"
                      />
                    </div>
                  </div>
                  <div className="form-group mb-3">
                    <div className=" ">
                      <input
                        className="form-control text-center"
                        type="number"
                        required=""
                        value={phone}
                       onChange={handleParamPhone}
                        placeholder="phone"
                      />
                    </div>
                  </div>
                  <div className="form-group mb-3">
                    <div className=" ">
                      <input
                        className="form-control text-center"
                        type="text"
                        required=""
                        value={loc}
                       onChange={handleParamLoc}
                        placeholder="loc"
                      />
                    </div>
                  </div>
                 
                 
                  <div className="form-group text-center mt-4 mb-3">
                    <div className="col-xs-12">
                      <button
                        className="
                          btn btn-info
                          d-block
                          w-100
                          waves-effect waves-light
                        "
                        onClick={handleSubmit}
                      >
                        Add worker
                      </button>
                    </div>
                  </div>
                 
              
                </div>
         
           
              </div>
         
          </div>
     
      </div>
               
        </div>
        <footer className="footer text-center">
          All Rights Reserved by Adminpro admin.
        </footer>
      
      </div>
     
    </div>
        
        
      </div>
    )
}
