import React from 'react'
import Head from "next/head";
import Nav from "./Nav";
import Tables from "./Tables";
import styles from "../../styles/Home.module.css";
export default function Homeo() {
    return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />

        <script
          async
          src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
        ></script>
        <script
          async
          src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"
        ></script>
     
      </Head>    
    
             <div className="preloader">
     </div>

      <div id="main-wrapper">
        <header className="topbar">
          <nav className="navbar top-navbar navbar-expand-md navbar-dark">
            <div className="navbar-header">
              <a
                className="nav-toggler waves-effect waves-light d-block d-md-none"
                
              >
                <i className="ri-close-line fs-6 ri-menu-2-line"></i>
              </a>

              <a
                className="navbar-brand"
                href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/html/main/index.html"
              >
      

               
              </a>

              <a
                className="topbartoggler d-block d-md-none waves-effect waves-light"
               
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <i data-feather="more-horizontal" className="feather-sm"></i>
              </a>
            </div>

           
          </nav>
        </header>

        <Nav />

        <div className="page-wrapper">
          <div className="container-fluid">
        
            <div className="row">
              <div className="col-lg-3 col-md-6">
                <div className="card bg-info">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                   
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Income</h6>
                        <h2 className="mt-0 text-white">953,000</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-success">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                     
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Expense</h6>
                        <h2 className="mt-0 text-white">236,000</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-primary">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                     
                     
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Assets</h6>
                        <h2 className="mt-0 text-white">987,563</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-danger">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                     
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Staff</h6>
                        <h2 className="mt-0 text-white">987,563</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              <div className="col-lg-6 d-flex align-items-stretch">
                <div className="card w-100">
                  <div className="card-body">
                    <div className="d-md-flex">
                      <div>
                        <h3 className="card-title mb-1">
                          <span className="lstick d-inline-block align-middle"></span>
                          Sales Overview
                        </h3>
                      </div>
                      <div className="ms-auto">
                        <select className="form-select">
                          <option selected="">January 2021</option>
                          <option value="1">February 2021</option>
                          <option value="2">March 2021</option>
                          <option value="3">April 2021</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div className="bg-info stats-bar">
                    <div className="row">
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3 active">
                          <h6 className="text-white">Total Sales</h6>
                          <h3 className="text-white mb-0">$10,345</h3>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3">
                          <h6 className="text-white">This Month</h6>
                          <h3 className="text-white mb-0">$7,589</h3>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3">
                          <h6 className="text-white">This Week</h6>
                          <h3 className="text-white mb-0">$1,476</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="card-body mt-4">
                 
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div className="card w-100">
               
                  <div className="card-body">
                    <h3 className="font-weight-normal">
                      Business development of rules 2021
                    </h3>
                    <span className="badge bg-info rounded-pill">
                      Technology
                    </span>
                    <p className="mb-0 mt-3">
                      Titudin venenatis ipsum aciat. Vestibu ullamer quam.
                      nenatis ipsum ac feugiat. Ibulum ullamcorper.aciat.
                      Vestibu ullamer quam. nenatis
                    </p>
                    <div className="d-flex mt-2">
                      <button className="btn ps-0 btn-link">Read more</button>
                      <div className="ms-auto align-self-center">
                        <a  className="link me-2">
                          <i className="ri-heart-fill"></i>
                        </a>
                        <a  className="link me-2">
                          <i className="ri-share-fill"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div className="card w-100">
                  <div className="card-body">
                    <h4 className="card-title">
                      <span className="lstick d-inline-block align-middle"></span>
                      Visit Separation
                    </h4>
                   
                    <table className="table v-middle fs-3 mb-0 mt-4">
                      <tr>
                        <td>Mobile</td>
                        <td className="text-end font-weight-medium">38.5%</td>
                      </tr>
                      <tr>
                        <td>Tablet</td>
                        <td className="text-end font-weight-medium">30.8%</td>
                      </tr>
                      <tr>
                        <td>Desktop</td>
                        <td className="text-end font-weight-medium">7.7%</td>
                      </tr>
                      <tr>
                        <td>Other</td>
                        <td className="text-end font-weight-medium">23.1%</td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              <div className="col-lg-4">
                <div className="card bg-success text-white">
                  <div className="card-body">
                    <div className="d-flex">
                      <div className="stats">
                        <h1 className="text-white">9062+</h1>
                        <h6 className="text-white">Subscribe</h6>
                        <button
                          className="
                          btn btn-rounded btn-outline btn-light
                          m-t-10
                          fs-3
                        "
                        >
                          Check list
                        </button>
                      </div>
                      <div className="stats-icon text-end ms-auto">
                        <i className="ri-mail-line display-5 op-3 text-dark"></i>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card bg-primary text-white">
                  <div className="card-body">
                    <div className="d-flex">
                      <div className="stats">
                        <h1 className="text-white">6509+</h1>
                        <h6 className="text-white">Facebook Likes</h6>
                        <button
                          className="
                          btn btn-rounded btn-outline btn-light
                          m-t-10
                          fs-3
                        "
                        >
                          Check list
                        </button>
                      </div>
                      <div className="stats-icon text-end ms-auto">
                        <i className="ri-facebook-fill display-5 op-3 text-dark"></i>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card bg-info text-white">
                  <div className="card-body">
                    <div className="d-flex">
                      <div className="stats">
                        <h1 className="text-white">3257+</h1>
                        <h6 className="text-white">Twitter Followers</h6>
                        <button
                          className="
                          btn btn-rounded btn-outline btn-light
                          m-t-10
                          fs-3
                        "
                        >
                          Check list
                        </button>
                      </div>
                      <div className="stats-icon text-end ms-auto">
                        <i className="ri-twitter-fill display-5 op-3 text-dark"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-8">
                <div className="card">
                  <div className="card-body">
                    <div className="d-md-flex">
                      <h4 className="card-title">
                        <span className="lstick d-inline-block align-middle"></span>
                        Website Visit
                      </h4>
                      <ul className="list-inline mb-0 ms-auto">
                        <li className="list-inline-item">
                          <h6 className="text-success">
                            <i
                              className="
                              ri-checkbox-blank-circle-fill
                              align-middle
                              fs-4
                              font-10
                              me-2
                            "
                            ></i>
                            Site A view
                          </h6>
                        </li>
                        <li className="list-inline-item">
                          <h6 className="text-info">
                            <i
                              className="
                              ri-checkbox-blank-circle-fill
                              align-middle
                              fs-4
                              font-10
                              me-2
                            "
                            ></i>
                            Site B view
                          </h6>
                        </li>
                      </ul>
                    </div>
                    <div className="text-center mt-3">
                      <div
                        className="btn-group"
                        role="group"
                        aria-label="Basic example"
                      >
                        <button
                          type="button"
                          className="
                          btn btn-sm btn-outline-secondary
                          shadow-sm
                          fs-2
                          me-0
                        "
                        >
                          PAGEVIEWS
                        </button>
                        <button
                          type="button"
                          className="btn btn-sm btn-outline-secondary shadow-sm fs-2"
                        >
                          REFERRALS
                        </button>
                      </div>
                    </div>
                    <div
                      id="Website-Visit"
                      className="position-relative mt-3"
                      style={{ height: "350px", width: "100%" }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>
           
         </div>

          <footer className="footer text-center">
            All Rights Reserved by Adminpro admin.
          </footer>
        </div>
      </div>

      <aside className="customizer">
        <a  className="service-panel-toggle">
          <i data-feather="settings" className="feather-sm fa fa-spin"></i>
        </a>
        <div className="customizer-body">
          <ul className="nav customizer-tab" role="tablist">
            <li className="nav-item">
              <a
                className="nav-link active"
                id="pills-home-tab"
                data-bs-toggle="pill"
                
                role="tab"
                aria-controls="pills-home"
                aria-selected="true"
              >
                <i className="ri-tools-fill fs-6"></i>
              </a>
            </li>
            <li className="nav-item">
              <a
                className="nav-link"
                id="pills-profile-tab"
                data-bs-toggle="pill"
                
                role="tab"
                aria-controls="chat"
                aria-selected="false"
              >
                <i className="ri-message-3-line fs-6"></i>
              </a>
            </li>
            <li className="nav-item">
              <a
                className="nav-link"
                id="pills-contact-tab"
                data-bs-toggle="pill"
                role="tab"
                aria-controls="pills-contact"
                aria-selected="false"
              >
                <i className="ri-timer-line fs-6"></i>
              </a>
            </li>
          </ul>
          <div className="tab-content" id="pills-tabContent">
            <div
              className="tab-pane fade show active"
              id="pills-home"
              role="tabpanel"
              aria-labelledby="pills-home-tab"
            >
              <div className="p-3 border-bottom">
                <h5 className="font-weight-medium mb-2 mt-2">
                  Layout Settings
                </h5>
                <div className="form-check mt-3">
                  <input
                    type="checkbox"
                    name="theme-view"
                    className="form-check-input"
                    id="theme-view"
                  />
                  <label className="form-check-label" htmlFor="theme-view">
                    <span>Dark Theme</span>
                  </label>
                </div>
                <div className="form-check mt-2">
                  <input
                    type="checkbox"
                    className="sidebartoggler form-check-input"
                    name="collapssidebar"
                    id="collapssidebar"
                  />
                  <label className="form-check-label" htmlFor="collapssidebar">
                    <span>Collapse Sidebar</span>
                  </label>
                </div>
                <div className="form-check mt-2">
                  <input
                    type="checkbox"
                    name="sidebar-position"
                    className="form-check-input"
                    id="sidebar-position"
                  />
                  <label
                    className="form-check-label"
                    htmlFor="sidebar-position"
                  >
                    <span>Fixed Sidebar</span>
                  </label>
                </div>
                <div className="form-check mt-2">
                  <input
                    type="checkbox"
                    name="header-position"
                    className="form-check-input"
                    id="header-position"
                  />
                  <label className="form-check-label" htmlFor="header-position">
                    <span>Fixed Header</span>
                  </label>
                </div>
                <div className="form-check mt-2">
                  <input
                    type="checkbox"
                    name="boxed-layout"
                    className="form-check-input"
                    id="boxed-layout"
                  />
                  <label className="form-check-label" htmlFor="boxed-layout">
                    <span>Boxed Layout</span>
                  </label>
                </div>
              </div>
              <div className="p-3 border-bottom">
                <h5 className="font-weight-medium mb-2 mt-2">
                  Logo Backgrounds
                </h5>
                <ul className="theme-color m-0 p-0">
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin1"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin2"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin3"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin4"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin5"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-logobg="skin6"
                    ></a>
                  </li>
                </ul>
              </div>
              <div className="p-3 border-bottom">
                <h5 className="font-weight-medium mb-2 mt-2">
                  Navbar Backgrounds
                </h5>
                <ul className="theme-color m-0 p-0">
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin1"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin2"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin3"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin4"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin5"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-navbarbg="skin6"
                    ></a>
                  </li>
                </ul>
              </div>
              <div className="p-3 border-bottom">
                <h5 className="font-weight-medium mb-2 mt-2">
                  Sidebar Backgrounds
                </h5>
                <ul className="theme-color m-0 p-0">
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin1"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin2"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin3"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin4"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin5"
                    ></a>
                  </li>
                  <li className="theme-item list-inline-item me-1">
                    <a
                      
                      className="theme-link rounded-circle d-block"
                      data-sidebarbg="skin6"
                    ></a>
                  </li>
                </ul>
              </div>
            </div>

            <div
              className="tab-pane fade"
              id="chat"
              role="tabpanel"
              aria-labelledby="pills-profile-tab"
            >
              <ul className="mailbox list-style-none mt-3">
                <li>
                  <div className="message-center chat-scroll position-relative">
                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_1"
                      data-user-id="1"
                    >
                      <span className="user-img position-relative d-inline-block">
                       
                        <span className="profile-status rounded-circle online"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Pavan kumar</h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:30 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_2"
                      data-user-id="2"
                    >
                      <span className="user-img position-relative d-inline-block">
                   
                        <span className="profile-status rounded-circle busy"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Sonu Nigam</h5>
                        <span className="fs-2text-nowrap d-block text-muted text-truncate"></span>

                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:10 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_3"
                      data-user-id="3"
                    >
                      <span className="user-img position-relative d-inline-block">
                     
                        <span className="profile-status rounded-circle away"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Arijit Sinh</h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          I am a singer!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:08 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_4"
                      data-user-id="4"
                    >
                      <span className="user-img position-relative d-inline-block">
                 
                        <span className="profile-status rounded-circle offline"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Nirav Joshi</h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:02 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_5"
                      data-user-id="5"
                    >
                      <span className="user-img position-relative d-inline-block">
                    
                        <span className="profile-status rounded-circle offline"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Sunil Joshi</h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:02 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_6"
                      data-user-id="6"
                    >
                      <span className="user-img position-relative d-inline-block">
                       
                        <span className="profile-status rounded-circle offline"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">
                          Akshay Kumar
                        </h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:02 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_7"
                      data-user-id="7"
                    >
                      <span className="user-img position-relative d-inline-block">
                     
                        <span className="profile-status rounded-circle offline"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">Pavan kumar</h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:02 AM
                        </span>
                      </div>
                    </a>

                    <a
                      
                      className="
                      message-item
                      d-flex
                      align-items-center
                      border-bottom
                      px-3
                      py-2
                    "
                      id="chat_user_8"
                      data-user-id="8"
                    >
                      <span className="user-img position-relative d-inline-block">
                      
                        <span className="profile-status rounded-circle offline"></span>
                      </span>
                      <div className="w-75 d-inline-block v-middle ps-2">
                        <h5 className="message-title mb-0 mt-1">
                          Varun Dhavan
                        </h5>
                        <span
                          className="
                          fs-2
                          text-nowrap
                          d-block
                          text-muted text-truncate
                        "
                        >
                          Just see the my admin!
                        </span>
                        <span className="fs-2 text-nowrap d-block text-muted">
                          9:02 AM
                        </span>
                      </div>
                    </a>
                  </div>
                </li>
              </ul>
            </div>

            <div
              className="tab-pane fade p-3"
              id="pills-contact"
              role="tabpanel"
              aria-labelledby="pills-contact-tab"
            >
              <h6 className="mt-3 mb-3">Activity Timeline</h6>
              <div className="steamline">
                <div className="sl-item">
                  <div className="sl-left bg-success">
                    <i
                      data-feather="user"
                      className="feather-sm fill-white"
                    ></i>
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Meeting today <span className="sl-date"> 5pm</span>
                    </div>
                    <div className="desc">you can write anything</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left bg-info">
                    <i className="fas fa-image"></i>
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Send documents to Clark
                    </div>
                    <div className="desc">Lorem Ipsum is simply</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left">
                  
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Go to the Doctor{" "}
                      <span className="sl-date">5 minutes ago</span>
                    </div>
                    <div className="desc">Contrary to popular belief</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left">
               
                  </div>
                  <div className="sl-right">
                    <div>
                      <a >Stephen</a>
                      <span className="sl-date">5 minutes ago</span>
                    </div>
                    <div className="desc">Approve meeting with tiger</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left bg-primary">
                    <i
                      data-feather="user"
                      className="feather-sm fill-white"
                    ></i>
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Meeting today <span className="sl-date"> 5pm</span>
                    </div>
                    <div className="desc">you can write anything</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left bg-info">
                    <i className="fas fa-image"></i>
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Send documents to Clark
                    </div>
                    <div className="desc">Lorem Ipsum is simply</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left">
              
                  </div>
                  <div className="sl-right">
                    <div className="font-weight-medium">
                      Go to the Doctor{" "}
                      <span className="sl-date">5 minutes ago</span>
                    </div>
                    <div className="desc">Contrary to popular belief</div>
                  </div>
                </div>
                <div className="sl-item">
                  <div className="sl-left">
                 
                  </div>
                  <div className="sl-right">
                    <div>
                      <a >Stephen</a>
                      <span className="sl-date">5 minutes ago</span>
                    </div>
                    <div className="desc">Approve meeting with tiger</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </aside>
      <div className="chat-windows"></div>
      </div>
        
    )
}
