import React from "react";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Nav from "./Nav";
import { useRouter } from "next/router";
import Leftsidebar from "./LeftSidebar";
export default function Homeo({ href }) {
  const router = useRouter();
  const handleClick = (e) => {
    e.preventDefault();
    router.push(href);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"
        ></script>
      </Head>

      <div id="main-wrapper">
        <Nav />
        <Leftsidebar />
        <div className="page-wrapper">
          <div className="container-fluid">
            <div className="row">
              <div className="col-lg-3 col-md-6">
                <div className="card bg-info">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                        <img
                          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/icon/income-w.png"
                          alt="Income"
                        />
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Income</h6>
                        <h2 className="mt-0 text-white">953,000</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-success">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                        <img
                          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/icon/expense-w.png"
                          alt="Income"
                        />
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Expense</h6>
                        <h2 className="mt-0 text-white">236,000</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-primary">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                        <img
                          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/icon/assets-w.png"
                          alt="Income"
                        />
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Assets</h6>
                        <h2 className="mt-0 text-white">987,563</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6">
                <div className="card bg-danger">
                  <div className="card-body">
                    <div className="d-flex no-block">
                      <div className="me-3 align-self-center">
                        <img
                          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/icon/staff-w.png"
                          alt="Income"
                        />
                      </div>
                      <div className="align-self-center">
                        <h6 className="text-white mt-2 mb-0">Total Staff</h6>
                        <h2 className="mt-0 text-white">987,563</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              <div className="col-lg-6 d-flex align-items-stretch">
                <div className="card w-100">
                  <div className="card-body">
                    <div className="d-md-flex">
                      <div>
                        <h3 className="card-title mb-1">
                          <span className="lstick d-inline-block align-middle"></span>
                          Website visits
                        </h3>
                      </div>
                      <div className="ms-auto">
                        <select className="form-select">
                          <option selected="">January 2021</option>
                          <option value="1">February 2021</option>
                          <option value="2">March 2021</option>
                          <option value="3">April 2021</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div className="bg-info stats-bar">
                    <div className="row">
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3 active">
                          <h6 className="text-white">Total Sales</h6>
                          <h3 className="text-white mb-0">$10,345</h3>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3">
                          <h6 className="text-white">This Month</h6>
                          <h3 className="text-white mb-0">$7,589</h3>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4">
                        <div className="p-3">
                          <h6 className="text-white">This Week</h6>
                          <h3 className="text-white mb-0">$1,476</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="card-body mt-4">
                    <div
                      id="Sales-Overview"
                      className="position-relative"
                      style={{ height: "340px" }}
                    ></div>
                  </div>
                </div>
              </div>
              <div className="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div className="card w-100">
                  <img
                    className="card-img-top blog-img3"
                    src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/big/img1.jpg"
                    alt="Card image cap"
                  />
                  <div className="card-body">
                    <h3 className="font-weight-normal">
                      Business development of rules 2021
                    </h3>
                    <span className="badge bg-info rounded-pill">
                      Technology
                    </span>
                    <p className="mb-0 mt-3">
                      Titudin venenatis ipsum aciat. Vestibu ullamer quam.
                      nenatis ipsum ac feugiat. Ibulum ullamcorper.aciat.
                      Vestibu ullamer quam. nenatis
                    </p>
                    <div className="d-flex mt-2">
                      <button className="btn ps-0 btn-link">Read more</button>
                      <div className="ms-auto align-self-center">
                        <a className="link me-2">
                          <i className="ri-heart-fill"></i>
                        </a>
                        <a className="link me-2">
                          <i className="ri-share-fill"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div className="card w-100">
                  <div className="card-body">
                    <h4 className="card-title">
                      <span className="lstick d-inline-block align-middle"></span>
                      Visit Separation
                    </h4>
                    <div
                      id="Visit-Separation"
                      style={{ height: "270px", width: "100%" }}
                      className="d-flex justify-content-center align-items-center"
                    ></div>
                    <table className="table v-middle fs-3 mb-0 mt-4">
                      <tr>
                        <td>Mobile</td>
                        <td className="text-end font-weight-medium">38.5%</td>
                      </tr>
                      <tr>
                        <td>Tablet</td>
                        <td className="text-end font-weight-medium">30.8%</td>
                      </tr>
                      <tr>
                        <td>Desktop</td>
                        <td className="text-end font-weight-medium">7.7%</td>
                      </tr>
                      <tr>
                        <td>Other</td>
                        <td className="text-end font-weight-medium">23.1%</td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <footer className="footer text-center">
            All Rights Reserved by Adminpro admin.
          </footer>
        </div>
      </div>
    </div>
  );
}
