import React from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import { useRouter } from 'next/router'

export default function Leftsidebar({href}) {
  const router = useRouter()
  const handleClick = (e) => {
    e.preventDefault()
    router.push(href)
  }
    return ( 
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />

        <script
          async
          src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
        ></script>
        <script
          async
          src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"
        ></script>
     
      </Head>    
      <aside className="left-sidebar">
        <div className="scroll-sidebar flex flex-col">
         <div className='h-1/6'> </div>
          <nav className="sidebar-nav">
            <ul id="sidebarnav">
             
              <li className="sidebar-item">
                <a href={href} onClick={() => router.push('../../')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="home" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Home
                   </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="settings" className="settings-icon"></i>
                  <span className="hide-menu"
                    >Wash
                  </span>
                 
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="eye" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Maintenance
                    </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                 
                  aria-expanded="false"
                >
                  <i data-feather="monitor" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Dashboard
                 </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Workers')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="users" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Workers
                    </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                 
                  aria-expanded="false"
                >
                  <i data-feather="clipboard" className="feather-icon"></i>
                  <span className="hide-menu"
                    >History
                </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => router.push('/components/Login')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="log-out" className="feather-icon"></i>
                  <span className="hide-menu"
                    >LogOut
                    </span>
                </a>
             </li>
   
            </ul>
          </nav>
        </div>
      </aside>
    
      </div>
    )
}
