import React from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";

export default function Login() {
    return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />

        <script
          async
          src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
        ></script>
        <script
          async
          src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"
        ></script>
        <script
          async
          src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"
        ></script>
     
      </Head>    
      <div className="preloader">
        
      </div>
        <div
        className="
          auth-wrapper
          d-flex
          no-block
          justify-content-center
          align-items-center
        "
        style=
        {{  backgroundColor:"gray"
        }}
      >
        <div className="auth-box p-4 bg-white rounded">
          <div id="loginform">
            <div className="logo">
              <h3 className="box-title mb-3 text-center">Sign In</h3>
            </div>
           
            <div className="row">
              <div className="col-12">
                <form
                  className="form-horizontal mt-3 form-material"
                  id="loginform"
                  action="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/html/main/index.html"
                >
                  <div className="form-group mb-3">
                    <div className="">
                      <input
                        className="form-control"
                        type="text"
                        required=""
                        placeholder="Username"
                      />
                    </div>
                  </div>
                  <div className="form-group mb-4">
                    <div className="">
                      <input
                        className="form-control"
                        type="password"
                        required=""
                        placeholder="Password"
                      />
                    </div>
                  </div>
                  <div className="form-group">
                    <div className="d-flex">
                      <div className="checkbox checkbox-info pt-0">
                        <input
                          id="checkbox-signup"
                          type="checkbox"
                          className="material-inputs chk-col-indigo"
                        />
                        <label htmlFor="checkbox-signup"> Remember me </label>
                      </div>
                      <div className="ms-auto">
                        <a
                          
                          id="to-recover"
                          className="
                            link
                            font-weight-medium
                            d-flex
                            align-items-center
                          "
                          ><i className="ri-lock-line fs-5 me-1"></i> Forgot pwd?</a
                        >
                      </div>
                    </div>
                  </div>
                  <div className="form-group text-center mt-4 mb-3">
                    <div className="col-xs-12">
                      <button
                        className="
                          btn btn-info
                          d-block
                          w-100
                          waves-effect waves-light
                        "
                        type="submit"
                      >
                        Log In
                      </button>
                    </div>
                  </div>
                 
                  <div className="form-group mb-0 mt-4">
                    <div className="col-sm-12 justify-content-center d-flex">
                      <p>
                        Don't have an account?
                        <a
                          className="text-info font-weight-medium ms-1"
                          >Sign Up</a
                        >
                      </p>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div id="recoverform">
            <div className="logo">
              <h3 className="font-weight-medium mb-3">Recover Password</h3>
              <span className="text-muted"
                >Enter your Email and instructions will be sent to you!</span
              >
            </div>
            <div className="row mt-3 form-material">
              <form className="col-12" action="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/html/main/index.html">
                <div className="form-group row">
                  <div className="col-12">
                    <input
                      className="form-control"
                      type="email"
                      required=""
                      placeholder="Username"
                    />
                  </div>
                </div>
                <div className="row mt-3">
                  <div className="col-12">
                    <button
                      className="btn d-block w-100 btn-primary text-uppercase"
                      type="submit"
                      name="action"
                    >
                      Reset
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
  
    </div> 
    )
}
