import React, { useEffect, useState } from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import { useRouter } from 'next/router'
import axios from 'axios';
import Leftsidebar from './LeftSidebar';
import Nav from './Nav';
export default function Tables({href}) {
  const router = useRouter()
  const [tab,setTab]=useState([])
 
  useEffect(()=>{
    axios.get('http://localhost:3000/api/Request/findAllRequest')
    .then((res)=>{
      console.log(res.data);
      setTab(res.data)})
    .catch((err)=>console.log(err))
  },[])
  const handleClick = (e) => {
    e.preventDefault()
    router.push(href)
  }

    return (
      <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />
 </Head>    
 

    <div id="main-wrapper">
    
      
      <Leftsidebar />
      <div className="page-wrapper">
      
        <div className="container-fluid">
         
      
   
      
        <div className="flex flex-row">
               <div className="w-1/12 ">

               </div>
               <div className="w-10/12 flex flex-col ">
<div className="h-4/6 ">
           <div className="d-flex align-items-stretch">
             <div className="card w-100">
               <div className="card-body">
                 <div className="d-md-flex">
                   <div>
                     <h4 className="card-title">
                       <span className="lstick d-inline-block align-middle"></span
                       >ALL Requests
                     </h4>
                   </div>
                   <div className="ms-auto">
                     <select className="form-select">
                       <option selected="">January 2021</option>
                       <option value="1">February 2021</option>
                       <option value="2">March 2021</option>
                       <option value="3">April 2021</option>
                     </select>
                   </div>
                 </div>
                 <div className="table-responsive mt-3">
                   <table className="table v-middle no-wrap mb-0">
                     <thead>
                       <tr>
                         <th className="border-0" colSpan="2">service</th>
                         <th className="border-0"> position</th>
                         <th className="border-0">type of car</th>
                         <th className="border-0">type of wash</th>
                         <th className="border-0">username</th>
                         <th className="border-0">avaibility</th>

                       </tr>
                     </thead>
                     <tbody>
                       {
                          tab.map((e)=>(
                            <>
                           
     <tr>
                         <td style={{width: "50px"}}>
                           <span
                             ><img
                               src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                               alt="user"
                               width="50"
                               className="rounded-circle"
                           /></span>
                         </td>
                        
                         <td>{e.service}</td>
                         <td>{e.position}</td>
                         <td>{e.typeOfCar}</td>
                         <td>{e.typeOfWash}</td>
                         <td>{e.userId}</td>
                          <td></td>
                       </tr>
                  
                            </>
                          ))
                       }
                    </tbody>
                   </table>
                 </div>
               </div>
             </div>
           </div>
           </div>
           <div className="h-1/6 "></div>

        </div>
        
       </div>
  
        </div>
        
        <footer className="footer text-center">
          All Rights Reserved by Adminpro admin.
        </footer>
      
      </div>
     
    </div>
   <div className="chat-windows"></div>
        
        
      </div>
         )
}

 
