import React, { useEffect, useState } from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import axios from 'axios'
import Router from 'next/router'
export default function Workers({href}) {
  const [tab,setTab]=useState([])
  

 
  useEffect(()=>{
    axios.get('/api/Workers/findallWorkers')
    .then((res)=>{
      console.log(res.data)
      setTab(res.data)
    })
    .catch((err)=>{
      console.log(err)
    })
     },[])
    return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />
 <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"></script>
      </Head>    
 

    <div id="main-wrapper">
    
      <header className="topbar">
        <nav className="navbar top-navbar navbar-expand-md navbar-dark">
          <div className="navbar-header">
            <a
              className="nav-toggler waves-effect waves-light d-block d-md-none"
              
            >
              <i className="ri-close-line fs-6 ri-menu-2-line"></i>
            </a>
        
            <a className="navbar-brand" href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/html/main/index.html">
              <b className="logo-icon">
                 <i className="wi wi-sunset"></i> 
                
                
                
              </b>
              
              <span className="logo-text">
          
              
              </span>
            </a>
         
            <a
              className="topbartoggler d-block d-md-none waves-effect waves-light"
              
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
              ><i data-feather="more-horizontal" className="feather-sm"></i
            ></a>
          </div>
          
          <div className="navbar-collapse collapse" id="navbarSupportedContent">
           
            <ul className="navbar-nav me-auto">
              <li className="nav-item">
                <a
                  className="
                    nav-link
                    sidebartoggler
                    d-none d-md-block
                    waves-effect waves-dark
                  "
                  ><i data-feather="menu" className="feather-sm"></i
                ></a>
              </li>
            </ul>
           
            <ul className="navbar-nav justify-content-end">
        
              <li >
                <button className="nav-link dropdown-toggle waves-effect waves-dark" onClick={() => Router.replace('/components/AddWorker')} >Add Worker</button>
              </li>
           
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle waves-effect waves-dark"
              
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i data-feather="bell"></i>
                  <div className="notify">
                    <span className="heartbit"></span> <span className="point"></span>
                  </div>
                </a>
                <div
                  className="
                    dropdown-menu dropdown-menu-end
                    mailbox
                    dropdown-menu-animate-up
                  "
                >
                  <ul className="list-style-none">
                    <li>
                      <div className="border-bottom rounded-top py-3 px-4">
                        <div className="mb-0 font-weight-medium fs-4">
                          Notifications
                        </div>
                      </div>
                    </li>
                    <li>
                      <div
                        className="message-center notifications position-relative"
                        style={{height: "230px"}}
                      >
                        <a
                          
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="btn btn-light-danger text-danger btn-circle"
                          >
                            <i
                              data-feather="link"
                              className="feather-sm fill-white"
                            ></i>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Luanch Admin
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                                fw-normal
                                text-muted
                                mt-1
                              "
                              >Just see the my new admin!</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:30 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="
                              btn btn-light-success
                              text-success
                              btn-circle
                            "
                          >
                            <i
                              data-feather="calendar"
                              className="feather-sm fill-white"
                            ></i>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Event today
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                                fw-normal
                                text-muted
                                mt-1
                              "
                              >Just a reminder that you have event</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:10 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span className="btn btn-light-info text-info btn-circle">
                            <i
                              data-feather="settings"
                              className="feather-sm fill-white"
                            ></i>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Settings
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                                fw-normal
                                text-muted
                                mt-1
                              "
                              >You can customize this template as you want</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:08 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="
                              btn btn-light-primary
                              text-primary
                              btn-circle
                            "
                          >
                            <i
                              data-feather="users"
                              className="feather-sm fill-white"
                            ></i>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Pavan kumar
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                                fw-normal
                                text-muted
                                mt-1
                              "
                              >Just see the my admin!</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:02 AM</span
                            >
                          </div>
                        </a>
                      </div>
                    </li>
                    <li>
                      <a
                        className="nav-link border-top text-center text-dark pt-3"
                      >
                        <strong>Check all notifications</strong>
                        <i data-feather="chevron-right" className="feather-sm"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
             
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle waves-effect waves-dark"
                  id="2"
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i data-feather="inbox"></i>
                  <div className="notify">
                    <span className="heartbit"></span> <span className="point"></span>
                  </div>
                </a>
                <div
                  className="
                    dropdown-menu
                    mailbox
                    dropdown-menu-end dropdown-menu-animate-up
                  "
                  aria-labelledby="2"
                >
                  <ul className="list-style-none">
                    <li>
                      <div className="border-bottom rounded-top py-3 px-4">
                        <div className="mb-0 font-weight-medium fs-4">
                          You have 4 new messages
                        </div>
                      </div>
                    </li>
                    <li>
                      <div
                        className="message-center message-body position-relative"
                        style={{height: "230px"}}
                      >
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="user-img position-relative d-inline-block"
                          >
                           
                            <span
                              className="profile-status rounded-circle online"
                            ></span>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Pavan kumar
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                                fw-normal
                                text-muted
                                mt-1
                              "
                              >Just see the my admin!</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:30 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="user-img position-relative d-inline-block"
                          >
                           
                            <span
                              className="profile-status rounded-circle busy"
                            ></span>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Sonu Nigam
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                              "
                              >I've sung a song! See you at</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:10 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="user-img position-relative d-inline-block"
                          >
                           
                            <span
                              className="profile-status rounded-circle away"
                            ></span>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Arijit Sinh
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                              "
                              >I am a singer!</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:08 AM</span
                            >
                          </div>
                        </a>
                        <a
                          className="
                            message-item
                            d-flex
                            align-items-center
                            border-bottom
                            px-3
                            py-2
                          "
                        >
                          <span
                            className="user-img position-relative d-inline-block"
                          >
                            
                            <span
                              className="profile-status rounded-circle offline"
                            ></span>
                          </span>
                          <div className="w-75 d-inline-block v-middle ps-3">
                            <h5 className="message-title mb-0 mt-1 fs-3 fw-bold">
                              Pavan kumar
                            </h5>
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                time
                                text-truncate
                              "
                              >Just see the my admin!</span
                            >
                            <span
                              className="
                                fs-2
                                text-nowrap
                                d-block
                                subtext
                                text-muted
                              "
                              >9:02 AM</span
                            >
                          </div>
                        </a>
                      </div>
                    </li>
                    <li>
                      <a
                        className="nav-link border-top text-center text-dark pt-3"
                      >
                        <b>See all e-Mails</b>
                        <i data-feather="chevron-right" className="feather-sm"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
            
              <li className="nav-item dropdown mega-dropdown">
                <a
                  className="nav-link dropdown-toggle waves-effect waves-dark"
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  ><i data-feather="grid"></i
                ></a>
                <div className="dropdown-menu dropdown-menu-animate-up">
                  <div className="mega-dropdown-menu row">
                    <div className="col-lg-3 col-xlg-2 mb-4">
                      <h4 className="mb-3">CAROUSEL</h4>
                      <div
                        id="carouselExampleControls"
                        className="carousel slide carousel-dark"
                        data-bs-ride="carousel"
                      >
                        <div className="carousel-inner">
                          <div className="carousel-item active">
                            <img
                              className="d-block img-fluid"
                              src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/big/img1.jpg"
                              alt="First slide"
                            />
                          </div>
                          <div className="carousel-item">
                            <img
                              className="d-block img-fluid"
                              src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/big/img2.jpg"
                              alt="Second slide"
                            />
                          </div>
                          <div className="carousel-item">
                            <img
                              className="d-block img-fluid"
                              src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/big/img3.jpg"
                              alt="Third slide"
                            />
                          </div>
                        </div>
                        <a
                          className="carousel-control-prev"
                          role="button"
                          data-bs-slide="prev"
                        >
                          <span
                            className="carousel-control-prev-icon"
                            aria-hidden="true"
                          ></span>
                          <span className="visually-hidden">Previous</span>
                        </a>
                        <a
                          className="carousel-control-next"
                          role="button"
                          data-bs-slide="next"
                        >
                          <span
                            className="carousel-control-next-icon"
                            aria-hidden="true"
                          ></span>
                          <span className="visually-hidden">Next</span>
                        </a>
                      </div>
                    </div>
                    <div className="col-lg-3 mb-4">
                      <h4 className="mb-3">ACCORDION</h4>
                      <div
                        className="accordion accordion-flush"
                        id="accordionFlushExample"
                      >
                        <div className="accordion-item">
                          <h2 className="accordion-header" id="flush-headingOne">
                            <button
                              className="accordion-button collapsed"
                              type="button"
                              data-bs-toggle="collapse"
                              data-bs-target="#flush-collapseOne"
                              aria-expanded="false"
                              aria-controls="flush-collapseOne"
                            >
                              Accordion Item #1
                            </button>
                          </h2>
                          <div
                            id="flush-collapseOne"
                            className="accordion-collapse collapse"
                            aria-labelledby="flush-headingOne"
                            data-bs-parent="#accordionFlushExample"
                          >
                            <div className="accordion-body">
                              Anim pariatur cliche reprehenderit, enim eiusmod
                              high life accusamus terry richardson ad squid.
                            </div>
                          </div>
                        </div>
                        <div className="accordion-item">
                          <h2 className="accordion-header" id="flush-headingTwo">
                            <button
                              className="accordion-button collapsed"
                              type="button"
                              data-bs-toggle="collapse"
                              data-bs-target="#flush-collapseTwo"
                              aria-expanded="false"
                              aria-controls="flush-collapseTwo"
                            >
                              Accordion Item #2
                            </button>
                          </h2>
                          <div
                            id="flush-collapseTwo"
                            className="accordion-collapse collapse"
                            aria-labelledby="flush-headingTwo"
                            data-bs-parent="#accordionFlushExample"
                          >
                            <div className="accordion-body">
                              Anim pariatur cliche reprehenderit, enim eiusmod
                              high life accusamus terry richardson ad squid.
                            </div>
                          </div>
                        </div>
                        <div className="accordion-item">
                          <h2 className="accordion-header" id="flush-headingThree">
                            <button
                              className="accordion-button collapsed"
                              type="button"
                              data-bs-toggle="collapse"
                              data-bs-target="#flush-collapseThree"
                              aria-expanded="false"
                              aria-controls="flush-collapseThree"
                            >
                              Accordion Item #3
                            </button>
                          </h2>
                          <div
                            id="flush-collapseThree"
                            className="accordion-collapse collapse"
                            aria-labelledby="flush-headingThree"
                            data-bs-parent="#accordionFlushExample"
                          >
                            <div className="accordion-body">
                              Anim pariatur cliche reprehenderit, enim eiusmod
                              high life accusamus terry richardson ad squid.
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 mb-4">
                      <h4 className="mb-3">CONTACT US</h4>
                      <form>
                        <div className="mb-3 form-floating">
                          <input
                            type="text"
                            className="form-control"
                            id="exampleInputname1"
                            placeholder="Enter Name"
                          />
                          <label>Enter Name</label>
                        </div>
                        <div className="mb-3 form-floating">
                          <input
                            type="email"
                            className="form-control"
                            placeholder="Enter email"
                          />
                          <label>Enter Email address</label>
                        </div>
                        <div className="mb-3 form-floating">
                          <textarea
                            className="form-control"
                            id="exampleTextarea"
                            rows="3"
                            placeholder="Message"
                          ></textarea>
                          <label>Enter Message</label>
                        </div>
                        <button
                          type="submit"
                          className="btn px-4 rounded-pill btn-info"
                        >
                          Submit
                        </button>
                      </form>
                    </div>
                    <div className="col-lg-3 col-xlg-4 mb-4">
                      <h4 className="mb-3">List style</h4>
                      <ul className="list-style-none">
                        <li>
                          <a  className="font-weight-medium"
                            ><i
                              data-feather="check-circle"
                              className="feather-sm text-success me-2"
                            ></i>
                            You can give link</a
                          >
                        </li>
                        <li>
                          <a className="font-weight-medium"
                            ><i
                              data-feather="check-circle"
                              className="feather-sm text-success me-2"
                            ></i>
                            Give link</a
                          >
                        </li>
                        <li>
                          <a  className="font-weight-medium"
                            ><i
                              data-feather="check-circle"
                              className="feather-sm text-success me-2"
                            ></i>
                            Another Give link</a
                          >
                        </li>
                        <li>
                          <a  className="font-weight-medium"
                            ><i
                              data-feather="check-circle"
                              className="feather-sm text-success me-2"
                            ></i>
                            Forth link</a
                          >
                        </li>
                        <li>
                          <a  className="font-weight-medium"
                            ><i
                              data-feather="check-circle"
                              className="feather-sm text-success me-2"
                            ></i>
                            Another fifth link</a
                          >
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </li>
              
              <li className="nav-item dropdown">
                <a
                  className="
                    nav-link
                    dropdown-toggle
                    text-muted
                    waves-effect waves-dark
                  "
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i className="flag-icon flag-icon-us"></i
                ></a>
                <div
                  className="
                    dropdown-menu dropdown-menu-end dropdown-menu-animate-up
                  "
                >
                  <a className="dropdown-item" 
                    ><i className="flag-icon flag-icon-in"></i> India</a
                  >
                  <a className="dropdown-item" 
                    ><i className="flag-icon flag-icon-fr"></i> French</a
                  >
                  <a className="dropdown-item" 
                    ><i className="flag-icon flag-icon-cn"></i> China</a
                  >
                  <a className="dropdown-item" 
                    ><i className="flag-icon flag-icon-de"></i> Dutch</a
                  >
                </div>
              </li>
           
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle waves-effect waves-dark"
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <img
                    src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                    alt="user"
                    width="30"
                    className="profile-pic rounded-circle"
                  />
                </a>
                <div
                  className="
                    dropdown-menu dropdown-menu-end
                    user-dd
                    animated
                    flipInY
                  "
                >
                  <div
                    className="
                      d-flex
                      no-block
                      align-items-center
                      p-3
                      bg-primary
                      text-white
                      mb-2
                    "
                  >
                    <div className="">
                      <img
                        src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                        alt="user"
                        className="rounded-circle"
                        width="60"
                      />
                    </div>
                    <div className="ms-2">
                      <h4 className="mb-0 text-white">Steave Jobs</h4>
                      <p className="mb-0">varun@gmail.com</p>
                    </div>
                  </div>
                  <a className="dropdown-item" 
                    ><i
                      data-feather="user"
                      className="feather-sm text-info me-1 ms-1"
                    ></i>
                    My Profile</a
                  >
                  <a className="dropdown-item"
                    ><i
                      data-feather="credit-card"
                      className="feather-sm text-primary me-1 ms-1"
                    ></i>
                    My Balance</a
                  >
                  <a className="dropdown-item" 
                    ><i
                      data-feather="mail"
                      className="feather-sm text-success me-1 ms-1"
                    ></i>
                    Inbox</a
                  >
                  <div className="dropdown-divider"></div>
                  <a className="dropdown-item" 
                    ><i
                      data-feather="settings"
                      className="feather-sm text-warning me-1 ms-1"
                    ></i>
                    Account Setting</a
                  >
                  <div className="dropdown-divider"></div>
                  <a className="dropdown-item" 
                    ><i
                      data-feather="log-out"
                      className="feather-sm text-danger me-1 ms-1"
                    ></i>
                    Logout</a
                  >
                  <div className="dropdown-divider"></div>
                  <div className="pl-4 p-2">
                    <a
                      
                      className="btn d-block w-100 btn-primary rounded-pill"
                      >View Profile</a
                    >
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <aside className="left-sidebar">
        <div className="scroll-sidebar flex flex-col">
         <div className='h-1/6'> </div>
          <nav className="sidebar-nav">
            <ul id="sidebarnav">
             
              <li className="sidebar-item">
                <a href={href} onClick={() => Router.replace('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="home" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Wash
                   </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="settings" className="settings-icon"></i>
                  <span className="hide-menu"
                    >Repair
                  </span>
                 
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="eye" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Maintenance
                    </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                 
                  aria-expanded="false"
                >
                  <i data-feather="monitor" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Dashboard
                 </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Workers')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="users" className="feather-icon"></i>
                  <span className="hide-menu"
                    >Workers
                    </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Tables')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                 
                  aria-expanded="false"
                >
                  <i data-feather="clipboard" className="feather-icon"></i>
                  <span className="hide-menu"
                    >History
                </span>
                </a>
             </li>
             <li className="sidebar-item">
                <a onClick={() => Router.replace('/components/Login')}
                  className="sidebar-link has-arrow waves-effect waves-dark"
                  
                  aria-expanded="false"
                >
                  <i data-feather="log-out" className="feather-icon"></i>
                  <span className="hide-menu"
                    >LogOut
                    </span>
                </a>
             </li>
   
            </ul>
          </nav>
        </div>
      </aside>
     
      <div className="page-wrapper">
      
        <div className="container-fluid">
         
      
   
      
        <div className="flex flex-row">
               <div className="w-1/12 ">

               </div>
               <div className="w-10/12 flex flex-col ">
<div className="h-4/6 ">
           <div className="d-flex align-items-stretch">
             <div className="card w-100">
               <div className="card-body">
                 <div className="d-md-flex">
                   <div>
                     <h4 className="card-title">
                       <span className="lstick d-inline-block align-middle"></span
                       >ALL workers
                     </h4>
                   </div>
                   <div className="ms-auto">
                     <select className="form-select">
                       <option selected="">January 2021</option>
                       <option value="1">February 2021</option>
                       <option value="2">March 2021</option>
                       <option value="3">April 2021</option>
                     </select>
                   </div>
                 </div>
                 <div className="table-responsive mt-3">
                   <table className="table v-middle no-wrap mb-0">
                     <thead>
                       <tr>
                         <th className="border-0" colSpan="2">workes Name</th>
                         <th className="border-0">worker Email</th>
                         <th className="border-0">worker Phone</th>
                         <th className="border-0">worker Localisation</th>

                         <th className="border-0">worker avaibility</th>
                       </tr>
                     </thead>
                     <tbody>
                      {tab?.map((e)=>(
                        <>
                               <tr>
                               <td style={{width: "50px"}}>
                                 <span
                                   ><img
                                     src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                                     alt="user"
                                     width="50"
                                     className="rounded-circle"
                                 /></span>
                               </td>
                               <td>
                                 <h6 className="mb-0 font-weight-medium">{e.name}</h6>
                                 <small className="text-muted">Web Designer</small>
                               </td>
                               <td>{e.email}</td>
                               <td>{e.phone}</td>
                               <td>{e.localisation}</td>

                               <td>
                                 <span className="badge bg-success rounded-pill"
                                   >Low</span
                                 >
                               </td>
                             </tr>
                      </>
                      ))}
                      </tbody>
                   </table>
                 </div>
               </div>
             </div>
           </div>
           </div>
           <div className="h-1/6 "></div>

        </div>
        
       </div>
  
        </div>
        
        <footer className="footer text-center">
          All Rights Reserved by Adminpro admin.
        </footer>
      
      </div>
     
    </div>
   <div className="chat-windows"></div>
        
        
      </div> 
    )
}
