import React, { useEffect, useState } from 'react'
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import axios from 'axios'
import { useRouter } from 'next/router'
import Nav from './Nav';
import Leftsidebar from './LeftSidebar';
export default function Workers({href}) {
  const [tab,setTab]=useState([])
  const router = useRouter()
  const handleClick = (e) => {
    e.preventDefault()
    router.push(href)
  }
  function getStaticProps() {
 
  
  
   
  }
  useEffect(()=>{
    axios.get('/api/Workers/findallWorkers')
    .then((res)=>{
      console.log(res)
      setTab(res.data)
    })
    .catch((err)=>{
      console.log(err)
    })
     },[])
    return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="canonical"
          href="https://www.wrappixel.com/templates/adminpro/"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/favicon.png"
        />

        <link
          rel="stylesheet"
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.css"
        />
        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/css-chart/css-chart.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.css"
          rel="stylesheet"
        />

        <link
          href="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/css/style.min.css"
          rel="stylesheet"
        />
 <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jquery/dist/jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app.init.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/app-style-switcher.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/sparkline/sparkline.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/waves.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/sidebarmenu.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/feather.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/custom.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/libs/jvectormap/jquery-jvectormap.min.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/extra-libs/jvector/jquery-jvectormap-us-aea-en.js"></script>
    <script async src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/dist/js/pages/dashboards/dashboard3.js"></script>
      </Head>    
 

    <div id="main-wrapper">
    
     <Leftsidebar />
      <div className="page-wrapper">
      
        <div className="container-fluid">
         
      
   
      
        <div className="flex flex-row">
               <div className="w-1/12 ">

               </div>
               <div className="w-10/12 flex flex-col ">
<div className="h-4/6 ">
           <div className="d-flex align-items-stretch">
             <div className="card w-100">
               <div className="card-body">
                 <div className="d-md-flex">
                   <div>
                     <h4 className="card-title">
                       <span className="lstick d-inline-block align-middle"></span
                       >ALL workers
                     </h4>
                   </div>
                   <div className="ms-auto">
                     <select className="form-select">
                       <option selected="">January 2021</option>
                       <option value="1">February 2021</option>
                       <option value="2">March 2021</option>
                       <option value="3">April 2021</option>
                     </select>
                   </div>
                 </div>
                 <div className="table-responsive mt-3">
                   <table className="table v-middle no-wrap mb-0">
                     <thead>
                       <tr>
                         <th className="border-0" colSpan="2">workes Name</th>
                         <th className="border-0">worker Email</th>
                         <th className="border-0">worker Phone</th>
                         <th className="border-0">worker Localisation</th>

                         <th className="border-0">worker avaibility</th>
                       </tr>
                     </thead>
                     <tbody>
                      {tab.map((e)=>(
                        <>
                               <tr>
                               <td style={{width: "50px"}}>
                                 <span
                                   ><img
                                     src="https://demos.wrappixel.com/premium-admin-templates/bootstrap/adminpro-bootstrap/package/assets/images/users/1.jpg"
                                     alt="user"
                                     width="50"
                                     className="rounded-circle"
                                 /></span>
                               </td>
                               <td>
                                 <h6 className="mb-0 font-weight-medium">{e.name}</h6>
                                 <small className="text-muted">Web Designer</small>
                               </td>
                               <td>{e.email}</td>
                               <td>{e.phone}</td>
                               <td>{e.localisation}</td>

                               <td>
                                 <span className="badge bg-success rounded-pill"
                                   >Low</span
                                 >
                               </td>
                             </tr>
                      </>
                      ))}
                      </tbody>
                   </table>
                 </div>
               </div>
             </div>
           </div>
           </div>
           <div className="h-1/6 "></div>

        </div>
        
       </div>
  
        </div>
        
        <footer className="footer text-center">
          All Rights Reserved by Adminpro admin.
        </footer>
      
      </div>
     
    </div>
        
        
      </div> 
    )
}
